lidar_fusion:
  ros__parameters:
    image_subscriber: "/camera/image_raw"
    calib_subscriber: "/camera/calibration"
    lidar_subscriber: "/lidar/points"

    YOLO_model: "yolov5su.pt"
    technique: "average"
    reduction_factor: 0.5
    yolo_classes: [0]
    # 1 - person
    # 2 - car

    image_publisher: "/camera_lidar_fusion/result"
